---
title: "pneumo israel"
author: "Dan Weinberger"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(reshape2)
library(lubridate)
```

```{r}
carr1 <- read_excel('./DONOTSYNC/Carriage Export.xlsx',guess_max=10000)
carr1$date <- as.Date(paste(carr1$Year,carr1$Month,'01', sep='-'))
carr1$one <- 1
carr1$density <- carr1$Quantitative_Density_1
carr1$density[carr1$Result_1=='NEG'] <- 0

carr1$agec<- NA

carr1$agec[carr1$Agemth<6] <- 1

carr1$agec[carr1$Agemth<12 & carr1$Agemth>=6] <- 2

carr1$agec[carr1$Agemth<24 & carr1$Agemth>=12] <- 3

carr1$agec[carr1$Agemth>=24 ] <- 4

carr1$high_inv <- NA
carr1$high_inv[carr1$Serotype_1 %in% c('19B','10F','31','17F','20','7C','34','13','24A','23A','28A','19C','11B','7A','23B','35A','35C','37','12A','11A','42','33B','33D','9L','25A','10C','32','18B','15F','11C','18F','33C','22A','25F','39','28F','35F','21','16F','6C','35B','29','6D','15A','9A','19F','18A','46','15BC','6A','23F','9N','6B','4'
,'10B','9V','7B','14','10A','15B','15C')
] <- 0
carr1$high_inv[carr1$Serotype_1 %in% c('1','2','5','7F','12F','3','8','33F','27','33F','24F','19A','38','24B','18C','33A','22F')] <- 1


carr1.m <- melt(carr1[,c('date','density','one')], id.vars = c('date', 'density') )

carr1.c <- dcast(carr1.m, date ~ density, fun.aggregate = sum)

carr1.c$any <- apply(carr1.c[,2:7],1, sum)

carr1.c$prev.low.density <- (carr1.c$`1`+carr1.c$`2`)/carr1.c$any

carr1.c$prev.hi.density <- (carr1.c$`3` + carr1.c$`4`)/carr1.c$any

all.dates <- cbind.data.frame('date'=seq.Date(from=min(carr1.c$date),
                                              to=max(carr1.c$date), by='month'))

carr1.c <- merge(carr1.c, all.dates, all=T)

#Stratified by age and ethnicity
carr2.m <- melt(carr1[,c('date','agec','Ethnicity','density','Result_1')], id.vars = c('date' ,'agec','Ethnicity', 'Result_1','density') )

carr2.c <- dcast(carr2.m, date+agec+Ethnicity ~ Result_1, fun.aggregate = length)

carr2.c$prev <- carr2.c$POS/(carr2.c$POS+carr2.c$NEG)


#Checks that dates are filled for all strata (shouldbe 8 strata total)--some strata has missing values; but this will be filled when merge with pneumonia, which does not have gaps
range(table(carr2.c$date))


```

CXR
```{r}
cx1 <- read_excel('./DONOTSYNC/X-rays Export.xlsx')

cx1$date <- as.Date(paste(cx1$Year,cx1$Month,'01', sep='-'))

cx1$one <- 1

cx1$agec<- NA

cx1$agec[cx1$Agemth<6] <- 1

cx1$agec[cx1$Agemth<12 & cx1$Agemth>=6] <- 2

cx1$agec[cx1$Agemth<24 & cx1$Agemth>=12] <- 3

cx1$agec[cx1$Agemth>=24 ] <- 4

cx1.m <- melt(cx1[,c('date',"CAAP_01" ,'one')], id.vars = c('date', "CAAP_01" ) )

cx1.c <- dcast(cx1.m, date ~ CAAP_01, fun.aggregate = sum)

all.dates <- cbind.data.frame('date'=seq.Date(from=min(cx1.c$date), to=max(cx1.c$date), 
                                              by='month'))

cx1.c <- merge(cx1.c, all.dates, all=T)

#Stratified by age and ethnicity
cx2.m <- melt(cx1[,c('date','agec','Ethnicity',"CAAP_01" ,'one')], id.vars = c('date', "CAAP_01" ,'agec','Ethnicity') )

cx2.c <- dcast(cx2.m, date+agec+Ethnicity ~ CAAP_01, fun.aggregate = sum)

#Checks that dates are filled for all strata (shouldbe 8 strata total)
range(table(cx2.c$date))



```


CXR
```{r}
vir1 <- read_excel('./DONOTSYNC/Viruses Export.xlsx')
vir1$detect  <- "none"
vir1$detect[vir1$Test_Result=='POS' ] <- vir1$Virus_tested[vir1$Test_Result=='POS' ]

vir1$date <- as.Date(paste(vir1$Year,vir1$Month,'01', sep='-'))

vir1$one <- 1

vir1$agec<- NA

vir1$agec[vir1$Agemth<6] <- 1

vir1$agec[vir1$Agemth<12 & vir1$Agemth>=6] <- 2

vir1$agec[vir1$Agemth<24 & vir1$Agemth>=12] <- 3

vir1$agec[vir1$Agemth>=24 ] <- 4

vir1.m <- melt(vir1[,c('date',"detect" ,'one')], id.vars = c('date', "detect" ) )

vir1.c <- dcast(vir1.m, date ~ detect, fun.aggregate = sum)

all.dates <- cbind.data.frame('date'=seq.Date(from=min(vir1.c$date),
                                              to=max(vir1.c$date), 
                                              by='month'))

vir1.c <- merge(vir1.c, all.dates, all=T)

#Stratified by age and ethnicity
vir2.m <- melt(vir1[,c('date','Ethnicity','agec',"detect" ,'one')], id.vars = c('date', "detect" ,'Ethnicity','agec') )

vir2.c <- dcast(vir2.m, date+agec+Ethnicity ~ detect, fun.aggregate = sum)

vir2.c$testN <- apply(vir2.c[, -c(1:3)],1,sum)
#Checks that dates are filled for all strata (shouldbe 8 strata total)
range(table(vir2.c$date))



```
Combine the virus, carriage and X-rays datasets
```{r}
all1 <- merge(cx2.c, carr2.c, by=c('Ethnicity', 'agec', 'date'), all=T)
all1 <- merge(all1, vir2.c, by=c('agec','Ethnicity', 'date'), all=T)

all1$Ethnicity <- as.factor(all1$Ethnicity)
all1$agec <- as.factor(all1$agec)

all1$caap.pre <- all1$CAAP
all1$caap.pre[all1$date>=as.Date('2020-03-01')] <- NA

all1$non.caap.pre <- all1$`Non-CAAP LRI`
all1$non.caap.pre[all1$date>=as.Date('2020-03-01')] <- NA

names(all1)[names(all1)=='Flu A'] <- 'FluA'
names(all1)[names(all1)=='Flu B'] <- 'FluB'

all1$t <- interval(min(all1$date), all1$date) %/% months(1) 
all1$sin12 <- sin(2*pi*all1$t/12)
all1$cos12 <- cos(2*pi*all1$t/12)

all1$sin6 <- sin(2*pi*all1$t/6)
all1$cos6 <- cos(2*pi*all1$t/6)

all1$year <- year(all1$date)
all1$month <- month(all1$date)

all1$epiyr <- all1$year
all1$epiyr[all1$month<=6] <- all1$year[all1$month<=6]  - 1 
all1$epiyr <- as.factor(all1$epiyr)

all1$month <- as.factor(all1$month)
```

scale each of teh viral variables to range 0-1 by age and ethnicity group
```{r}
all.spl <- split(all1, paste0(all1$Ethnicity, all1$agec))
all.spl <- lapply(all.spl, function(x){
  # x$Adeno <- x$Adeno/max(x$Adeno, na.rm=T)
  # x$FluA <- x$FluA/max(x$FluA, na.rm=T)
  # x$FluB <- x$FluB/max(x$FluB, na.rm=T)
  # x$hMPV <- x$hMPV/max(x$hMPV, na.rm=T)
  # x$Paraflu <- x$Paraflu/max(x$Paraflu, na.rm=T)
  # x$RSV <- x$RSV/max(x$RSV, na.rm=T)
  # x$testN <- x$testN/max(x$testN, na.rm=T)
  # x$none <- x$none/max(x$none, na.rm=T)
  
  x$Adeno <- x$Adeno/x$testN
  x$FluA <- x$FluA/x$testN
  x$FluB <- x$FluB/x$testN
  x$hMPV <- x$hMPV/x$testN
  x$Paraflu <- x$Paraflu/x$testN
  x$RSV <- x$RSV/x$testN
  #x$testN <- x$testN/x$testN
  x$none <- x$none/x$testN
  
  return(x)
})
all1 <- do.call('rbind.data.frame', all.spl)

```

```{r, fig.width=5, fig.height=8}
par(mfrow=c(2,1))
plot(carr1.c$date, carr1.c$prev.low.density, ylim=c(0,0.4),type='l', bty='l', main='low density')
abline(v=as.Date('2020-03-01'), lty=2, col='grey')
plot(carr1.c$date, carr1.c$prev.hi.density, type='l', ylim=c(0,0.4), bty='l')
abline(v=as.Date('2020-03-01'), lty=2, col='grey', main='High density')

```

```{r}
carr1.m2 <- melt(carr1[,c('Year', 'Month','density','one')], id.vars = c('Year', 'Month', 'density') )
carr1.c2 <- acast(carr1.m2, Year~Month ~ density, fun.aggregate = sum)
N.samples <-  apply(carr1.c2,c(1:2), sum)
N.low.density <- apply(carr1.c2[,,2:4],c(1:2), sum)
N.hi.density <- apply(carr1.c2[,,5],c(1:2), sum)
N.Any.density <- apply(carr1.c2[,,2:5],c(1:2), sum)

# N.samples <- N.samples[,c(6:12, 1:5)]
# N.low.density <- N.low.density[,c(6:12, 1:5)]
# N.hi.density <- N.hi.density[,c(6:12, 1:5)]
# N.Any.density <- N.Any.density[,c(6:12, 1:5)]

```


```{r, fig.width=5, fig.height=8}
par(mfrow=c(2,1))
matplot(t(N.low.density/N.samples), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4), main='Low density colonization 1-3' )

matplot(t(N.hi.density/N.samples), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4),main='High density colonization 4' )

matplot(t(N.Any.density/N.samples), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.6), main='Any colonization')

```
##Ethnicity 
```{r}
carr1.m2 <- melt(carr1[,c('Year', 'Month','density','one','Ethnicity')], id.vars = c('Year', 'Month', 'density','Ethnicity') )
carr1.c2 <- acast(carr1.m2, Ethnicity~Year~Month ~ density, fun.aggregate = sum)
N.samples <-  apply(carr1.c2,c(1:3), sum)
N.low.density <- apply(carr1.c2[,,,2:4],c(1:3), sum)
N.hi.density <- apply(carr1.c2[,,,5],c(1:3), sum)
N.Any.density <- apply(carr1.c2[,,,2:5],c(1:3), sum)
```

```{r, fig.width=5, fig.height=8}
for(i in c("Jewish",'Bedouin')){
par(mfrow=c(2,1))
matplot(t(N.low.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4), main=paste0('Low density colonization 1-3 ',i))

matplot(t(N.hi.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4),main=paste0('High density colonization 4 ',i))
}

par(mfrow=c(2,1))
for(i in c("Jewish",'Bedouin')){

matplot(t(N.Any.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.6), main=paste0('Any colonization ',i))
}
```
##Age 
```{r}
carr1.m2 <- melt(carr1[,c('Year', 'Month','density','one','agec')], id.vars = c('Year', 'Month', 'density','agec') )
carr1.c2 <- acast(carr1.m2, agec~Year~Month ~ density, fun.aggregate = sum)
N.samples <-  apply(carr1.c2,c(1:3), sum)
N.low.density <- apply(carr1.c2[,,,2:4],c(1:3), sum)
N.hi.density <- apply(carr1.c2[,,,5],c(1:3), sum)
N.Any.density <- apply(carr1.c2[,,,2:5],c(1:3), sum)
```


```{r, fig.width=5, fig.height=8}
agelabs <- c('<6m','6-11m', '12-23m','24+m')
for(i in c(1:4)){
par(mfrow=c(2,1))
matplot(t(N.low.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4), main=paste0('Low density colonization 1-3 ',agelabs[i]))

matplot(t(N.hi.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.4),main=paste0('High density colonization 4 ',agelabs[i]))
}
```
```{r, fig.width=6, fig.height=6}

par(mfrow=c(2,2))
for(i in c(1:4)){

matplot(t(N.Any.density[i,,]/N.samples[i,,]), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,0.7), main=paste0('Any colonization ',agelabs[i]))
}
```



```{r}
plot(cx1.c$`Non-CAAP LRI`, type='l')
plot(cx1.c$CAAP, type='l')
```

## Invasiveness
```{r}
carr1.m2 <- melt(carr1[,c('Year', 'Month','high_inv','one')], id.vars = c('Year', 'Month', 'high_inv') )
carr1.c2 <- acast(carr1.m2, Year~Month ~ high_inv, fun.aggregate = sum)
N.samples <-  apply(carr1.c2,c(1:2), sum)
N.low.inv <- apply(carr1.c2[,,'0'],c(1:2), sum)
N.hi.inv <- apply(carr1.c2[,,'1'],c(1:2), sum)

# N.samples <- N.samples[,c(6:12, 1:5)]
# N.low.density <- N.low.density[,c(6:12, 1:5)]
# N.hi.density <- N.hi.density[,c(6:12, 1:5)]
# N.Any.density <- N.Any.density[,c(6:12, 1:5)]

```


```{r, fig.width=5, fig.height=8}
par(mfrow=c(2,1))
matplot(t(N.low.inv/N.samples), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,max(N.low.inv/N.samples, na.rm=T)), main='Low invasiveness colonization' )

matplot(t(N.hi.inv/N.samples), type='l', col=c(rep('grey',4), 'red'), bty='l',ylim=c(0,max(N.hi.inv/N.samples, na.rm=T)),main='High invasiveness colonization' )

```


## Regression model
Note there is no population size included here. And

```{r}


lapply(all.spl, function(x){
plot(x$date, x$Adeno, type='l')
points(x$date, x$caap.pre/max(x$caap.pre, na.rm=T), type='l', col='blue')
points(x$date, x$RSV, type='l', col='red')
})
```

```{r}
all1$month <- as.factor(month(all1$date))
all1$prev.lo <- (all1$`1` + all1$`2` + all1$`3`)/(all1$`0`+all1$`1` + all1$`2` + all1$`3` + all1$`4`)

all1$prev.hi <- (all1$`4`)/(all1$`0`+all1$`1` + all1$`2` + all1$`3` + all1$`4`)

 #plot(all1$prev.lo, all1$prev.hi)
 

```

function to test each virus one by one or in combination
```{r}
#Viral panel for all; rhino only started 2019 so exclude here
viruses <- c('none','FluA','FluB','RSV','Adeno','hMPV', 'FluA+FluB', 'FluA+FluB+RSV','FluA+FluB+RSV+hMPV','RSV+none', 'Adeno+testN', 'RSV+Adeno','RSV+Adeno+none','testN','testN+RSV', 'RSV+hMPV','Adeno+hMPV', 'FluA+FluB+RSV+Adeno', 'FluA+FluB+RSV+Adeno + hMPV'  ) #paraflu
all1$one <-1

mod.func <- function(outcome){
    mod1 <- lapply(viruses, function(x){
      eqn<- as.formula(paste0(outcome, ' ~ agec + Ethnicity + epiyr  + month+',x
                 #,'+',  ' (',  x , ')*agec 
                  #(',  x , ')*Ethnicity' 
                  ))
     mod1 <- lm( eqn, data=all1)
     })
    r2.mod1 <- cbind.data.frame(viruses, 'r2'=sapply(mod1, function(x) summary(x)$adj.r.squared))
    aic.mod1 <- cbind.data.frame(viruses, 'AIC'=sapply(mod1,function(x) AIC(x)))
    
    all1.pre <- all1[!is.na(all1[,outcome]),]
    all.norsv <- all1.pre
    all.noflu <- all1.pre
    all.noadeno <- all1.pre
    all.nohmpv<- all1.pre
    all.novirus <- all1.pre
    
    all.norsv$RSV <- 0
    all.noflu$FluA <- 0
    all.noflu$FluB <- 0
    all.noadeno$Adeno <- 0
    all.nohmpv$hMPV <- 0
    
    all.novirus$Adeno <- 0
    all.novirus$RSV <- 0
    all.novirus$FluA <- 0
    all.novirus$FluB <- 0
    all.novirus$hMPV <- 0
    
    pred1 <-sapply(mod1, function(x) predict(x, newdata=all1.pre))
    pred1.norsv <-sapply(mod1, function(x) predict(x, newdata=all.norsv))
    pred1.noflu <-sapply(mod1, function(x) predict(x, newdata=all.noflu))
    pred1.nohmpv <-sapply(mod1, function(x) predict(x, newdata=all.nohmpv))
    pred1.noadeno <-sapply(mod1, function(x) predict(x, newdata=all.noadeno))

        pred1.novirus <-sapply(mod1, function(x) predict(x, newdata=all.novirus))
    
    pred1.sum <- apply(pred1,2,sum)
    pred1.norsv.sum <- apply(pred1.norsv,2,sum)
    pred1.noflu.sum <- apply(pred1.noflu,2,sum)
    pred1.noadeno.sum <- apply(pred1.noadeno,2,sum)
    pred1.novirus.sum <- apply(pred1.novirus,2,sum)
    pred1.nohmpv.sum <- apply(pred1.nohmpv,2,sum)
    
    attrib.pct.rsv <- (pred1.sum-pred1.norsv.sum)/pred1.sum * 100
    attrib.pct.flu <- (pred1.sum-pred1.noflu.sum)/pred1.sum * 100
    attrib.pct.adeno <- (pred1.sum-pred1.noadeno.sum)/pred1.sum * 100
    attrib.pct.hmpv <- (pred1.sum-pred1.nohmpv.sum)/pred1.sum * 100

    attrib.pct.virus <- (pred1.sum-pred1.novirus.sum)/pred1.sum * 100
    
    attrib.pct.combined <-
      cbind.data.frame(attrib.pct.rsv,attrib.pct.flu,attrib.pct.adeno,attrib.pct.hmpv, attrib.pct.virus)
    attrib.pct.combined$model <- viruses

    
    #Stratified
      all.preds <-  list(pred1,pred1.norsv,pred1.noflu,pred1.noadeno,pred1.nohmpv,pred1.novirus)
      
      names(all.preds) <- c('overall','norsv','noflu', 'noadeno','nohmpv', 'novirus')
      
    pred.strata.age.eth <- lapply(all.preds, function(pred.ds){
              aggregate(pred.ds, 
                                 by=list('agec'=all1.pre$agec,
                                         'Ethnicity'=all1.pre$Ethnicity),
                                 FUN=sum)
    })
    pred.strata.age <- lapply(all.preds, function(pred.ds){
              aggregate(pred.ds, 
                                 by=list('agec'=all1.pre$agec),
                                 FUN=sum)
    })

    #By age and ethnicity
   attrib.pcts.age.eth <- lapply(pred.strata.age.eth[-1], function(x){
      ds1 <-cbind.data.frame(pred.strata.age.eth[[1]][,c(1:2)], ((pred.strata.age.eth[[1]][,-c(1:2)]) - x[,-c(1:2)])/(pred.strata.age.eth[[1]][,-c(1:2)])*100 )
     names(ds1) <- c('agec','ethnicity',viruses)
  return(ds1)
                 })
   names(attrib.pcts.age.eth) <- names(pred.strata.age.eth[-1])
   
   #By age
      attrib.pcts.age <- lapply(pred.strata.age[-1], function(x){
      ds1 <-cbind.data.frame(pred.strata.age[[1]][,c(1)], ((pred.strata.age[[1]][,-c(1)]) - x[,-c(1)])/(pred.strata.age[[1]][,-c(1)])*100 )
     names(ds1) <- c('agec',viruses)
  return(ds1)
                 })
   names(attrib.pcts.age) <- names(pred.strata.age[-1])
   
    out.list <- list('attrib.pcts.age'=attrib.pcts.age,'attrib.pcts.age.eth'=attrib.pcts.age.eth, 'aic.mod1'=aic.mod1,'mod1'=mod1)
    return(out.list)
}

```

```{r}

attrib.pct.caap <- mod.func("caap.pre")
attrib.pct.non.caap <- mod.func("non.caap.pre")

#Modle with RSV only
attrib.pct.caap$attrib.pcts.age$norsv[,c('agec','RSV')]
attrib.pct.non.caap$attrib.pcts.age$norsv[,c('agec','RSV')]

attrib.pct.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV")]
attrib.pct.non.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV")]

#Model with RSV +hMPV
attrib.pct.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV+hMPV")]
attrib.pct.non.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV+hMPV")]

attrib.pct.caap$attrib.pcts.age.eth$nohmpv[,c('agec','ethnicity',"RSV+hMPV")]
attrib.pct.non.caap$attrib.pcts.age.eth$nohmpv[,c('agec','ethnicity',"RSV+hMPV")]



##Model with RSV +adeno
attrib.pct.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV+Adeno")]
attrib.pct.non.caap$attrib.pcts.age.eth$norsv[,c('agec','ethnicity',"RSV+Adeno")]

attrib.pct.caap$attrib.pcts.age.eth$noadeno[,c('agec','ethnicity',"RSV+Adeno")]
attrib.pct.non.caap$attrib.pcts.age.eth$noadeno[,c('agec','ethnicity',"RSV+Adeno")]

#Novirus
attrib.pct.caap$attrib.pcts.age.eth$novirus[,c('agec','ethnicity',"FluA+FluB+RSV+Adeno + hMPV")]
attrib.pct.non.caap$attrib.pcts.age.eth$novirus[,c('agec','ethnicity',"FluA+FluB+RSV+Adeno + hMPV")]


```

#test
```{r}
mod1 <- lm( caap.pre~  RSV   +month + agec * Ethnicity * t, data=all1)
summary(mod1)
pred.ds <- all1
pred.ds$pred1 <- predict(mod1,newdata=all1, type='response')
all1.norsv <- pred.ds
all1.norsv$RSV <- 0
pred.ds$pred.norsv <-  predict(mod1,newdata=all1.norsv, type='response')

(sum(pred.ds$pred1) -sum(pred.ds$pred.norsv))/sum(pred.ds$pred1)

pred.ds.spl <- split(pred.ds, paste0(pred.ds$agec,pred.ds$Ethnicity))


lapply( names(pred.ds.spl), function(x){
  ds <- pred.ds.spl[[x]]
  plot(ds$date, ds$CAAP , type='l', bty='l', col='gray', main=x)
  points(ds$date, ds$pred1, col='blue', type='l')
  points(ds$date, ds$pred.norsv, col='red', type='l')
})

```

```{r}
all1$log.rsv <- log(all1$RSV+0.5)
  mod1 <- glm.nb(caap.pre ~ agec + Ethnicity + sin12 + cos12 +  sin6 + cos6+ log.rsv + log.rsv*agec , data=all1)
  
summary(mod1)

mod2 <- lm(caap.pre ~ agec + Ethnicity + sin12 + cos12 +  sin6 + cos6+ RSV + RSV*Ethnicity + RSV*agec, data=all1)
  
summary(mod2)

```

## Function for log-linked model
```{r}

mod.func.log <- function(outcome){
    mod1 <- lapply(viruses, function(x){
      eqn<- as.formula(paste0(outcome, ' ~ agec + Ethnicity + sin12 + cos12 +  sin6 + cos6+ epiyr*agec*Ethnicity+',x , '+ (',  x , ')*Ethnicity'
                 #,'+',' ' (',  x , ')*agec + 
                  #(',  x , ')*Ethnicity' 
                  ))
     mod1 <- glm.nb( eqn, data=all1)
     })
    aic.mod1 <- cbind.data.frame(viruses, 'AIC'=sapply(mod1,function(x) AIC(x)))
    
    all1.pre <- all1[!is.na(all1[,outcome]),]
    all.norsv <- all1.pre
    all.noflu <- all1.pre
    all.noadeno <- all1.pre
    all.nohmpv<- all1.pre
    all.novirus <- all1.pre
    
    all.norsv$RSV <- 0
    all.noflu$FluA <- 0
    all.noflu$FluB <- 0
    all.noadeno$Adeno <- 0
    all.nohmpv$hMPV <- 0
    
    all.novirus$Adeno <- 0
    all.novirus$RSV <- 0
    all.novirus$FluA <- 0
    all.novirus$FluB <- 0
    all.novirus$hMPV <- 0
    
    pred1 <-sapply(mod1, function(x) predict(x, newdata=all1.pre, type='response'))
    pred1.norsv <-sapply(mod1, function(x) predict(x, newdata=all.norsv, type='response'))
    pred1.noflu <-sapply(mod1, function(x) predict(x, newdata=all.noflu, type='response'))
    pred1.nohmpv <-sapply(mod1, function(x) predict(x, newdata=all.nohmpv, type='response'))
    pred1.noadeno <-sapply(mod1, function(x) predict(x, newdata=all.noadeno, type='response'))

        pred1.novirus <-sapply(mod1, function(x) predict(x, newdata=all.novirus, type='response'))
    
    pred1.sum <- apply(pred1,2,sum)
    pred1.norsv.sum <- apply(pred1.norsv,2,sum)
    pred1.noflu.sum <- apply(pred1.noflu,2,sum)
    pred1.noadeno.sum <- apply(pred1.noadeno,2,sum)
    pred1.novirus.sum <- apply(pred1.novirus,2,sum)
    pred1.nohmpv.sum <- apply(pred1.nohmpv,2,sum)
    
    attrib.pct.rsv <- (pred1.sum-pred1.norsv.sum)/pred1.sum * 100
    attrib.pct.flu <- (pred1.sum-pred1.noflu.sum)/pred1.sum * 100
    attrib.pct.adeno <- (pred1.sum-pred1.noadeno.sum)/pred1.sum * 100
    attrib.pct.hmpv <- (pred1.sum-pred1.nohmpv.sum)/pred1.sum * 100

    attrib.pct.virus <- (pred1.sum-pred1.novirus.sum)/pred1.sum * 100
    
    attrib.pct.combined <-
      cbind.data.frame(attrib.pct.rsv,attrib.pct.flu,attrib.pct.adeno, attrib.pct.virus)
    attrib.pct.combined$model <- viruses

    
    #Stratified
    pred1.strat <- aggregate(pred1, 
                                 by=list('agec'=all1.pre$agec,
                                         'Ethnicity'=all1.pre$Ethnicity),
                                 FUN=sum)
    pred1.strat.flu <- aggregate(pred1.noflu,
                                     by=list('agec'=all1.pre$agec,
                                             'Ethnicity'=all1.pre$Ethnicity),
                                     FUN=sum)
    pred1.strat.rsv <- aggregate(pred1.norsv,
                                     by=list('agec'=all1.pre$agec,
                                             'Ethnicity'=all1.pre$Ethnicity),
                                     FUN=sum)
    pred1.strat.adeno <- aggregate(pred1.noadeno,
                                     by=list('agec'=all1.pre$agec,
                                             'Ethnicity'=all1.pre$Ethnicity),
                                     FUN=sum)
    
    pred1.strat.hmpv <- aggregate(pred1.nohmpv,
                                     by=list('agec'=all1.pre$agec,
                                             'Ethnicity'=all1.pre$Ethnicity),
                                     FUN=sum)
    
    
    pred1.strat.novirus <- aggregate(pred1.novirus,
                                     by=list('agec'=all1.pre$agec,
                                             'Ethnicity'=all1.pre$Ethnicity),
                                     FUN=sum)
attrib.pct.rsv.strat <-cbind.data.frame(pred1.strat[,c(1:2)], (pred1.strat[,-c(1:2)]-pred1.strat.rsv[,-c(1:2)])/pred1.strat[,-c(1:2)] * 100)
   attrib.pct.flu.strat <-cbind.data.frame(pred1.strat[,c(1:2)], (pred1.strat[,-c(1:2)]-pred1.strat.flu[,-c(1:2)])/pred1.strat[,-c(1:2)] * 100)
attrib.pct.adeno.strat <-cbind.data.frame(pred1.strat[,c(1:2)], (pred1.strat[,-c(1:2)]-pred1.strat.adeno[,-c(1:2)])/pred1.strat[,-c(1:2)] * 100)
attrib.pct.hmpv.strat <-cbind.data.frame(pred1.strat[,c(1:2)], (pred1.strat[,-c(1:2)]-pred1.strat.hmpv[,-c(1:2)])/pred1.strat[,-c(1:2)] * 100)
attrib.pct.virus.strat <-cbind.data.frame(pred1.strat[,c(1:2)], (pred1.strat[,-c(1:2)]-pred1.strat.novirus[,-c(1:2)])/pred1.strat[,-c(1:2)] * 100)
names(attrib.pct.virus.strat) <- c('agec','ethnicity',viruses)

    
    out.list <- list('attrib.pct.combined'=attrib.pct.combined,'attrib.pct.virus.strat'=attrib.pct.virus.strat, 'aic.mod1'=aic.mod1,'mod1'=mod1, 'pred1.strat'=pred1.strat)
    return(out.list)
}

```

```{r}
attrib.pct.caap <- mod.func.log("caap.pre")
attrib.pct.non.caap <- mod.func.log("non.caap.pre")

attrib.pct.caap$attrib.pct.combined

attrib.pct.non.caap$attrib.pct.combined

attrib.pct.caap$attrib.pct.virus.strat

attrib.pct.non.caap$attrib.pct.virus.strat
```




Include carriage
```{r}
mod1 <- glm( caap.pre ~ 
              month + Ethnicity +
              RSV + 
               agec+
               prev.lo
              , data=all1, family=gaussian)
summary(mod1)

all1$pred1 <- predict(mod1, newdata=all1, type='response')


all1.m <- melt(all1[,c('CAAP','pred1','date','agec','Ethnicity')], id.vars=c('date','agec','Ethnicity'))
all1.c <- acast(all1.m, agec~Ethnicity~date~variable)

all.dates <- as.Date(dimnames(all1.c)[[3]])
for(i in dimnames(all1.c)[[1]]){
  for(j in dimnames(all1.c)[[2]]){
plot(all.dates,all1.c[i,j,,'CAAP'], type='l', bty='l', main=paste(i,j))
points(all.dates,all1.c[i,j,,'pred1'], type='l', col='gray')
  }
}


```
Just do fully-stratified model
```{r}
all.spl <- split(all1, cbind.data.frame(all1$agec, all1$Ethnicity))

mod2 <- lapply(all.spl, function(x){
  mods <- glm( caap.pre ~ 
              sin12 + cos12 + sin6 + cos6+
              prev.lo+
               RSV +
               RSV*prev.lo
         
              , data=x, family=gaussian)
})

summary1 <- lapply(mod2, summary)
pred1 <- mapply(predict, mod2, newdata=all.spl, SIMPLIFY=F )

for(i in 1:length(all.spl)){
plot(all.spl[[i]]$date, all.spl[[i]]$CAAP, type='l')
points(all.spl[[i]]$date, pred1[[i]], type='l', col='red')
}
```



